name: Deploy BAPD to Heroku with fresh data

on:
  workflow_dispatch:
  schedule:
  - cron: '1 12 * * *'

jobs:

  bapd-fetch-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch the latest data
        run: python -m bapd_opendb.app --init

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku plugins:install heroku-builds
          datasette publish heroku BAPD_OPENDB.db --name test-bapd-opendb -m metadata.json
